---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: Europe/Zagreb
lsi: false
markdown: kramdown


### content configuration ###
title:       "Simpozij studenata farmacije i medicinske biokemije (FARMEBS)"
keywords:    "farmebs, simpozij, farmaceutsko-biokemijski fakultet, fbf, sveuciliste u zagrebu, unizg"
description: "Symposium webpage"
source_link: "https://github.com/kiferd/farmebs-wp"
# favicon:     "img/favicon.ico"
# touch_icon:  "img/apple-touch-icon.png"
# google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
### https://coolors.co/ was used
colors:
  black:        '#1f271b'
  white:        '#fefefe'
  # white:        '#F1EDEE'  # Isabelline
  red:          '#bd373d'  # Cardinal
  green:        '#3e7840'  # Fern Green
  purple:       '#533a71'  # Cyber Grape
  # skobeloff:    '#216869'
  # baby-powder:  '#f0f4ef'

kramdown:
  auto_ids:  false

