---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: Europe/Zagreb
lsi: false
markdown: kramdown


### content configuration ###
title:       "Simpozij studenata farmacije i medicinske biokemije (FARMEBS)"
keywords:    "farmebs, simpozij, farmaceutsko-biokemijski fakultet, fbf, sveuciliste u zagrebu, unizg"
description: "Symposium website"
<<<<<<< HEAD
source_link: "https://kiferd.github.io/farmebs-wp"
baseurl: "https://kiferd.github.io/farmebs-wp"
=======
source_link: "https://github.com/kiferd/farmebs-wp"
>>>>>>> 136c272 (Fix source_link again)
# favicon:     "img/favicon.ico"
# touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: "G-470DRCR4K2"


### template colors, used site-wide via css ###
### https://coolors.co/ was used
colors:
  black:        '#1f271b'
  white:        '#fefefe'
  red:          '#bd373d'  # Cardinal
  green:        '#3e7840'  # Fern Green
  purple:       '#533a71'  # Cyber Grapes

kramdown:
  auto_ids:  false

