---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: Europe/Zagreb
lsi: false
markdown: kramdown


### content configuration ###
title:       "Simpozij studenata farmacije i medicinske biokemije (FARMEBS)"
keywords:    "farmebs, simpozij, farmaceutsko-biokemijski fakultet, fbf, sveuciliste u zagrebu, unizg"
description: "Symposium website"
source_link: "https://github.com/kiferd/farmebs-wp"
url: "https://farmebs.pharma.hr"
# favicon:     "img/favicon.ico"
# touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: "UA-196856557-1"

### Multilingual settings ###
default_lang: "hr"  # Default language (Croatian)
languages: ["hr", "en"]  # Supported languages
lang_dir: ["hr", "en"]  # Keep empty unless you want language directories for each site


### template colors, used site-wide via css ###
### https://coolors.co/ was used
colors:
  black:        '#1f271b'
  white:        '#fefefe'
  red:          '#bd373d'  # Cardinal
  green:        '#3e7840'  # Fern Green
  purple:       '#533a71'  # Cyber Grapes
  grey:         '#d7d9d7'  # Light grey

kramdown:
  auto_ids:  false

